[package]
name = "sniffy"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
chrono = "0.4.38"
serde = "1.0.215"
serde_json = "1.0"
mysql = "*"
sha2 = "0.10.8"

[build-dependencies]
bindgen = "0.69.5"
